services:
  db: 
    image: postgres:15
    container_name: postgres-persistente
    environment:
      POSTGRES_PASSWORD: mipassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: