FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app
EXPOSE 8080
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package


FROM eclipse-temurin:17-jre-alpine 
COPY --from=builder /app/target/*.jar app.jar
CMD [ "java", "-jar", "app.jar" ]